name: gift_manager
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.4"


dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.4
  cupertino_icons: ^1.0.5
  provider: ^6.0.3
  google_fonts: ^3.0.1
  uuid: ^3.0.6
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
  share_plus: ^4.0.10


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
